### PR TITLE
add button and misc fixes

### LINKED ISSUE #50: create a Le Chat specific Button component
Implement a Le Chat specific button component that uses an underlying Chakra button, but which, when imported, comes in already styled/themed as we want it to be.

### PR DESCRIPTION
**Pull request by marcgaj**
resolves #50

### CODE REVIEW

File: client/src/theme.js [hunk 1]
```diff
@@ -54,6 +54,7 @@ const customTheme = {
     turquoise,
     red,
     gray,
+    ...theme.colors,
```
Comment (Tyresius92) [inline client/src/theme.js:57]: let's move this to the top so we're not overwriting if we have any name conflicts down the line.

Comment (marcgaj) [reply client/src/theme.js]: image

**Comment by Tyresius92** [comment]
@all-contributors please add @marcgaj for code changes
